// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int Times = Integer.parseInt(args[0]);
		double roll;
		int Sum = 0;
		for (int i=0; i<Times; i++)
		{
			roll = Math.random();
			roll = Math.round(roll);
			Sum += roll;
		}

		System.out.println("> 0.5:  " + (Times-Sum) + " times");
		System.out.println("<= 0.5: " + Sum + " times");

		if (Sum != 0)
		{
			double Ratio = (double)(Times-Sum)/Sum;
			System.out.println("ratio:  " + Ratio);
		}
	    // Replace this comment with your code
	}
}
